version: '2'
services:
  biggest-monuments:
    image: node:8.8-alpine
    working_dir: /app
    command: npm start
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      NODE_ENV: dev
    volumes:
      - .:/app

  ngnix:
    image: nginx:latest
    links:
      - biggest-monuments
    depends_on:
      - biggest-monuments
    ports:
      - "81:80"

